# -------------------------------------------------------------------------------
# -- Filename 		: led_array.tcl
# -- Title    		: LED Array Wiring 
# -- Author   		: Patrick Zwahlen
# -- Date     		: 07.01.2020
# -- Projectname	: VHDL-Projekt_RPN-Rechner_Zwahlen_Streit
# -------------------------------------------------------------------------------
#Please do not remove the below two lines as they are required to use one of the 120/108 LED's
set_global_assignment -name RESERVE_NCEO_AFTER_CONFIGURATION "USE AS REGULAR IO"
set_global_assignment -name CYCLONEII_RESERVE_NCEO_AFTER_CONFIGURATION "USE AS REGULAR IO"

# You have to replace <ENTITY_PORT_NAME_xxx> with the name of the Output port
# of your top entity

set_location_assignment PIN_E6 -to led_matrix1[1]
set_location_assignment PIN_J16 -to led_matrix1[2]
set_location_assignment PIN_K16 -to led_matrix1[3]
set_location_assignment PIN_J17 -to led_matrix1[4]
set_location_assignment PIN_K17 -to led_matrix1[5]
set_location_assignment PIN_J18 -to led_matrix1[6]
set_location_assignment PIN_K18 -to led_matrix1[7]
set_location_assignment PIN_F19 -to led_matrix1[8]
set_location_assignment PIN_J15 -to led_matrix1[9]
set_location_assignment PIN_K15 -to led_matrix1[10]
set_location_assignment PIN_L16 -to led_matrix1[11]
set_location_assignment PIN_L15 -to led_matrix1[12]

set_location_assignment PIN_D6 -to led_matrix2[1]
set_location_assignment PIN_H9 -to led_matrix2[2]
set_location_assignment PIN_F10 -to led_matrix2[3]
set_location_assignment PIN_G12 -to led_matrix2[4]
set_location_assignment PIN_E10 -to led_matrix2[5]
set_location_assignment PIN_G14 -to led_matrix2[6]
set_location_assignment PIN_G15 -to led_matrix2[7]
set_location_assignment PIN_G16 -to led_matrix2[8]
set_location_assignment PIN_F14 -to led_matrix2[9]
set_location_assignment PIN_J22 -to led_matrix2[10]
set_location_assignment PIN_K21 -to led_matrix2[11]
set_location_assignment PIN_D19 -to led_matrix2[12]

set_location_assignment PIN_E5 -to led_matrix3[1]
set_location_assignment PIN_F8 -to led_matrix3[2]
set_location_assignment PIN_G10 -to led_matrix3[3]
set_location_assignment PIN_F11 -to led_matrix3[4]
set_location_assignment PIN_E9 -to led_matrix3[5]
set_location_assignment PIN_H13 -to led_matrix3[6]
set_location_assignment PIN_H14 -to led_matrix3[7]
set_location_assignment PIN_H15 -to led_matrix3[8]
set_location_assignment PIN_G17 -to led_matrix3[9]
set_location_assignment PIN_J21 -to led_matrix3[10]
set_location_assignment PIN_F15 -to led_matrix3[11]
set_location_assignment PIN_F17 -to led_matrix3[12]

set_location_assignment PIN_B5 -to led_matrix4[1]
set_location_assignment PIN_G8 -to led_matrix4[2]
set_location_assignment PIN_H10 -to led_matrix4[3]
set_location_assignment PIN_E11 -to led_matrix4[4]
set_location_assignment PIN_G7 -to led_matrix4[5]
set_location_assignment PIN_G13 -to led_matrix4[6]
set_location_assignment PIN_D10 -to led_matrix4[7]
set_location_assignment PIN_F12 -to led_matrix4[8]
set_location_assignment PIN_H16 -to led_matrix4[9]
set_location_assignment PIN_H19 -to led_matrix4[10]
set_location_assignment PIN_E15 -to led_matrix4[11]
set_location_assignment PIN_D17 -to led_matrix4[12]

set_location_assignment PIN_C4 -to led_matrix5[1]
set_location_assignment PIN_E7 -to led_matrix5[2]
set_location_assignment PIN_G9 -to led_matrix5[3]
set_location_assignment PIN_H11 -to led_matrix5[4]
set_location_assignment PIN_F7 -to led_matrix5[5]
set_location_assignment PIN_H12 -to led_matrix5[6]
set_location_assignment PIN_F9 -to led_matrix5[7]
set_location_assignment PIN_E12 -to led_matrix5[8]
set_location_assignment PIN_E13 -to led_matrix5[9]
set_location_assignment PIN_H17 -to led_matrix5[10]
set_location_assignment PIN_D15 -to led_matrix5[11]
set_location_assignment PIN_K22 -to led_matrix5[12]

set_location_assignment PIN_A4 -to led_matrix6[1]
set_location_assignment PIN_C7 -to led_matrix6[2]
set_location_assignment PIN_A8 -to led_matrix6[3]
set_location_assignment PIN_A10 -to led_matrix6[4]
set_location_assignment PIN_A14 -to led_matrix6[5]
set_location_assignment PIN_A16 -to led_matrix6[6]
set_location_assignment PIN_A18 -to led_matrix6[7]
set_location_assignment PIN_B20 -to led_matrix6[8]
set_location_assignment PIN_B22 -to led_matrix6[9]
set_location_assignment PIN_E22 -to led_matrix6[10]
set_location_assignment PIN_H21 -to led_matrix6[11]
set_location_assignment PIN_L21 -to led_matrix6[12]

set_location_assignment PIN_C3 -to led_matrix7[1]
set_location_assignment PIN_A5 -to led_matrix7[2]
set_location_assignment PIN_B7 -to led_matrix7[3]
set_location_assignment PIN_B9 -to led_matrix7[4]
set_location_assignment PIN_C13 -to led_matrix7[5]
set_location_assignment PIN_C15 -to led_matrix7[6]
set_location_assignment PIN_C17 -to led_matrix7[7]
set_location_assignment PIN_C19 -to led_matrix7[8]
set_location_assignment PIN_A20 -to led_matrix7[9]
set_location_assignment PIN_D20 -to led_matrix7[10]
set_location_assignment PIN_F20 -to led_matrix7[11]
set_location_assignment PIN_F16 -to led_matrix7[12]

set_location_assignment PIN_B3 -to led_matrix8[1]
set_location_assignment PIN_C6 -to led_matrix8[2]
set_location_assignment PIN_A7 -to led_matrix8[3]
set_location_assignment PIN_A9 -to led_matrix8[4]
set_location_assignment PIN_B13 -to led_matrix8[5]
set_location_assignment PIN_B15 -to led_matrix8[6]
set_location_assignment PIN_B17 -to led_matrix8[7]
set_location_assignment PIN_B19 -to led_matrix8[8]
set_location_assignment PIN_C21 -to led_matrix8[9]
set_location_assignment PIN_D21 -to led_matrix8[10]
set_location_assignment PIN_F22 -to led_matrix8[11]
set_location_assignment PIN_E16 -to led_matrix8[12]

set_location_assignment PIN_A3 -to led_matrix9[1]
set_location_assignment PIN_B6 -to led_matrix9[2]
set_location_assignment PIN_C8 -to led_matrix9[3]
set_location_assignment PIN_C10 -to led_matrix9[4]
set_location_assignment PIN_A13 -to led_matrix9[5]
set_location_assignment PIN_A15 -to led_matrix9[6]
set_location_assignment PIN_A17 -to led_matrix9[7]
set_location_assignment PIN_A19 -to led_matrix9[8]
set_location_assignment PIN_B21 -to led_matrix9[9]
set_location_assignment PIN_D22 -to led_matrix9[10]
set_location_assignment PIN_F21 -to led_matrix9[11]
set_location_assignment PIN_L22 -to led_matrix9[12]

set_location_assignment PIN_B4 -to led_matrix10[1]
set_location_assignment PIN_A6 -to led_matrix10[2]
set_location_assignment PIN_B8 -to led_matrix10[3]
set_location_assignment PIN_B10 -to led_matrix10[4]
set_location_assignment PIN_B14 -to led_matrix10[5]
set_location_assignment PIN_B16 -to led_matrix10[6]
set_location_assignment PIN_B18 -to led_matrix10[7]
set_location_assignment PIN_C20 -to led_matrix10[8]
set_location_assignment PIN_C22 -to led_matrix10[9]
set_location_assignment PIN_E21 -to led_matrix10[10]
set_location_assignment PIN_H22 -to led_matrix10[11]
set_location_assignment PIN_H20 -to led_matrix10[12]
